### ISSUE TITLE
Comentário sobre a apresentação

### ISSUE THREAD

**Issue by fccoelho** [wellington36/Modelling-the-dynamics-of-language-death#5]
@wellington36 Gostei bastante da sua apresentação. Ficou bem estruturada e fácil de entender. 

Sobre a inferência Bayesiana, faltou mostrar os dados que você utilizou para cada língua antes de apresentar os resultados da estimação. A multi-modalidade nas posteriores estimadas para o Welsh indicam que faltam dados para fazer uma estimação adequada.

Por fim, sugiro que  na apresentação da curva de S(t), que vc apresente na figura, a incerteza, ou seja os intervalos de credibilidade da mesma. Isto pode ser feito por meio de amostras da distribuição posterior de S(t). procure exemplos [aqui](https://docs.pymc.io/en/v3/nb_examples/index.html) 

Se tiver interesse em continuar este trabalho para TCC podemos conversar.

**Comment by wellington36** [comment]
Sim, de fato, nessa parte da curva S(t) já ia adicionar o r2 (calculado via sklearn), modificar o t0 para ser um parametro (me parece que isso melhora um pouco) e adicionar isso:

![image](https://user-images.githubusercontent.com/61877847/142926654-de53c5b9-d63c-46ed-ad8e-df9f63a61de1.png)

essa parte dos intervalos de credibilidade acho que ainda não entendi como seria isso no `pymc3`.

Sobre o TCC, gostei bastante de fazer esse trabalho acho que pode ser uma boa, mas acho que prefiro estudar um pouco mais esse assunto e dar uma resposta mais certa daqui um tempo.

**Comment by wellington36** [comment]
E também eu basicamente tomei distribuições a priori como Uniform para os parametros e ajustei os intervalos, provavelmente estudar distribuições a priori melhores vão dar melhores resultados.

**Comment by fccoelho** [comment]
Sim mudar as prioris pode melhorar o ajuste, mas é preciso também justificar a escolha de prioris, isto pode ser um bom ponto para a discussão do trabalho.

**Comment by wellington36** [comment]
Quando me refiro a mudar as prioris penso em algo mais formal pesquisando em artigos na área, como não encontrei muitos trabalhos sobre morte de idioma (principalmente usando prioris e posterioris) provavelmente procuraria em trabalhos que descrevem epidemias. Bom provavelmente discutirei isso um pouco no fim. Ademais, me parece um trabalho divertido para TCC, mas devo pensar melhor nisso.

**Comment by wellington36** [comment]
Quando me refiro a mudar as prioris penso em algo mais formal pesquisando em artigos na área, como não encontrei muitos trabalhos sobre morte de idioma (principalmente usando prioris e posterioris) provavelmente procuraria em trabalhos que descrevem epidemias. Bom provavelmente discutirei isso um pouco no fim. Ademais, me parece um trabalho divertido para TCC, mas devo pensar melhor nisso.

**Comment by wellington36** [comment]
No caso, investigar melhores prioris para o caso, verificar como se "adaptão" a modelagem (nesse caso estou atribuindo se "adaptão" como tem um r2 melhor). Num trabalho futuro, também é interresante tentar encontrar dados melhores (o que não é fácil).

**Comment by wellington36** [comment]
Também tem esse livro [The Extinction of the World's Languages (2000)](https://books.google.com.br/books?hl=en&lr=&id=k2TnCwAAQBAJ&oi=fnd&pg=PR5&dq=Daniel+Nettle,+Suzanne+Romaine+-+Vanishing+Voices+The+Extinction+of+the+World%27s+Languages+(2000)&ots=V4JIFyN4Ff&sig=b_3-SYvAJ4TFDi1ugaXW-vNMn_A#v=onepage&q=Daniel%20Nettle%2C%20Suzanne%20Romaine%20-%20Vanishing%20Voices%20The%20Extinction%20of%20the%20World's%20Languages%20(2000)&f=false) que provavelmente tem muita coisa para acrecentar a esse trabalho.
